// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-b2Valna0YkeHmV1EGFFmmBVKvjVqv0A',
    appId: '1:509219125212:web:a38588e63aa081aaeac119',
    messagingSenderId: '509219125212',
    projectId: 'sf-movie-app',
    authDomain: 'sf-movie-app.firebaseapp.com',
    storageBucket: 'sf-movie-app.firebasestorage.app',
    measurementId: 'G-6LXC0F5ELG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAF-3HCO1GTAJ3KVvTYkO4ISS1VswFA0Lo',
    appId: '1:509219125212:android:b5e101f58ac4f7cbeac119',
    messagingSenderId: '509219125212',
    projectId: 'sf-movie-app',
    storageBucket: 'sf-movie-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDykUnVGLNb6FGaEp894W02GQUAm9EdLkw',
    appId: '1:509219125212:ios:77b850bd581d02c0eac119',
    messagingSenderId: '509219125212',
    projectId: 'sf-movie-app',
    storageBucket: 'sf-movie-app.firebasestorage.app',
    iosBundleId: 'com.example.sfmovie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDykUnVGLNb6FGaEp894W02GQUAm9EdLkw',
    appId: '1:509219125212:ios:77b850bd581d02c0eac119',
    messagingSenderId: '509219125212',
    projectId: 'sf-movie-app',
    storageBucket: 'sf-movie-app.firebasestorage.app',
    iosBundleId: 'com.example.sfmovie',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-b2Valna0YkeHmV1EGFFmmBVKvjVqv0A',
    appId: '1:509219125212:web:6215d40509519f48eac119',
    messagingSenderId: '509219125212',
    projectId: 'sf-movie-app',
    authDomain: 'sf-movie-app.firebaseapp.com',
    storageBucket: 'sf-movie-app.firebasestorage.app',
    measurementId: 'G-QQ3TWH4YP7',
  );
}
